# Site settings
title: TM Web
logo: /assets/img/logo.png
email: nil
description: ""
baseurl: "/jekyll"
url: "https://takashi-matsushita.github.io" # the base hostname & protocol
production_url: "https://takashi-matsushita.github.io/jekyll"
BASE_PATH: "https://takashi-matsushita.github.io/jekyll"

twitter_username: nil
github_username:  takashi-matsushita

# Build settings
published: true
show_downloads: false
google_analytics: UA-45695282-2
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
theme: jekyll-theme-minimal
github: [metadata]
encoding: UTF-8
plugins:
  - jekyll-feed
pages_list:
  Post: '/post'
  About: '/about'
  Categories: '/categories'
